### ISSUE TITLE
Maven Dependecy Scanning not working in JDK 11 Maven Dependency Plugin >3.1

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/sonarqube-licensecheck#35]
When running with JDK 11 and Maven Dependency Plugin >3.1 the dependency scanning fails with exceptions like this

```
[WARNING] Could not parse Maven POM \.m2\repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.9.8\jackson-module-parameter-names-2.9.8.jar -- module com.fasterxml.jackson.module.pom
java.io.FileNotFoundException: \.m2\repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.9.8\jackson-module-parameter-names-2.9.8.jar -- module com.fasterxml.jackson.module.pom (Could not find file)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at at.porscheinformatik.sonarqube.licensecheck.maven.LicenseFinder.getLicenses(LicenseFinder.java:30)
        at at.porscheinformatik.sonarqube.licensecheck.maven.MavenDependencyScanner.lambda$loadLicenseFromPom$0(MavenDependencyScanner.java:183)
...
```

**Comment by derkoe** [comment]
The reason for this is that the Maven Dependency Plugin adds the module name to the output:

```
[INFO]    com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.8:compile:\.m2\repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.9.8\jackson-module-parameter-names-2.9.8.jar -- module com.fasterxml.jackson.module.paramnames [auto]
```
