### ISSUE TITLE
sonar-maven-plugin analysis fails with NoClassDefFoundError

### ISSUE THREAD

**Issue by zoledian** [porscheinformatik/sonarqube-licensecheck#39]
```
BUILD FAILURE
...
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project XYZ: Execution default-cli of goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar failed: A required class was missing while executing org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar: com/hazelcast/util/collection/ArrayUtils
...
Caused by: java.lang.NoClassDefFoundError: com/hazelcast/util/collection/ArrayUtils
  at at.porscheinformatik.sonarqube.licensecheck.ValidateLicenses.lambda$checkSpdxLicenseWithAnd$5(ValidateLicenses.java:132)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
```

sonarqube: 7.6
sonarqube-licensecheck: v3.0.0-beta-2
maven: 3.3.9
jdk: 1.8.0_152
sonar-maven-plugin: 3.6.0.1398

**Comment by derkoe** [comment]
OK that's definitely a bug!

**Comment by derkoe** [comment]
Release [v3.0.0-beta-3](https://github.com/porscheinformatik/sonarqube-licensecheck/releases/tag/v3.0.0-beta-3)
