### ISSUE TITLE
NPE 

### ISSUE THREAD

**Issue by Janpopan** [porscheinformatik/sonarqube-licensecheck#88]
Plugin Version 3.1-rc2 (and also others)
Sonar 7.6

I get a NPE. This happens with different repos . 

`29-Jul-2019 13:02:34	[INFO] 13:02:34.806 Sensor License Check [licensecheck]
29-Jul-2019 13:02:37	[WARNING] 13:02:37.312 Could not get dependency list via maven
29-Jul-2019 13:02:37	[INFO] ------------------------------------------------------------------------
29-Jul-2019 13:02:37	[INFO] Reactor Summary:
29-Jul-2019 13:02:37	[INFO] 
29-Jul-2019 13:02:37	[INFO] XXXX ........................................ FAILURE [01:13 min]
29-Jul-2019 13:02:37	[INFO] XXX .................................. SKIPPED
29-Jul-2019 13:02:37	[INFO] XXXX.......................... SKIPPED
29-Jul-2019 13:02:37	[INFO] ------------------------------------------------------------------------
29-Jul-2019 13:02:37	[INFO] BUILD FAILURE
29-Jul-2019 13:02:37	[INFO] ------------------------------------------------------------------------
29-Jul-2019 13:02:37	[INFO] Total time: 01:24 min
29-Jul-2019 13:02:37	[INFO] Finished at: 2019-07-29T13:02:37+02:00
29-Jul-2019 13:02:37	[INFO] Final Memory: 131M/1220M
29-Jul-2019 13:02:37	[INFO] ------------------------------------------------------------------------
29-Jul-2019 13:02:37	[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project de.bdr.goid: null: MojoExecutionException: NullPointerException -> [Help 1]
29-Jul-2019 13:02:37	org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project de.bdr.goid: null
29-Jul-2019 13:02:37	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
29-Jul-2019 13:02:37	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
29-Jul-2019 13:02:37	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
29-Jul-2019 13:02:37	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
29-Jul-2019 13:02:37	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
29-Jul-2019 13:02:37	        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
29-Jul-2019 13:02:37	        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
29-Jul-2019 13:02:37	        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
29-Jul-2019 13:02:37	        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
29-Jul-2019 13:02:37	        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
29-Jul-2019 13:02:37	        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
29-Jul-2019 13:02:37	        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
29-Jul-2019 13:02:37	        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
29-Jul-2019 13:02:37	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29-Jul-2019 13:02:37	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
29-Jul-2019 13:02:37	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29-Jul-2019 13:02:37	        at java.lang.reflect.Method.invoke(Method.java:498)
29-Jul-2019 13:02:37	        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
29-Jul-2019 13:02:37	        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
29-Jul-2019 13:02:37	        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
29-Jul-2019 13:02:37	        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
29-Jul-2019 13:02:37	Caused by: org.apache.maven.plugin.MojoExecutionException
29-Jul-2019 13:02:37	        at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:67)
29-Jul-2019 13:02:37	        at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:104)
29-Jul-2019 13:02:37	        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
29-Jul-2019 13:02:37	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
29-Jul-2019 13:02:37	        ... 20 more
29-Jul-2019 13:02:37	Caused by: java.lang.NullPointerException
29-Jul-2019 13:02:37	        at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:196)
29-Jul-2019 13:02:37	        at at.porscheinformatik.sonarqube.licensecheck.projectLicense.ProjectLicense.fromString(ProjectLicense.java:78)
29-Jul-2019 13:02:37	        at at.porscheinformatik.sonarqube.licensecheck.projectLicense.ProjectLicenseService.getProjectLicenseList(ProjectLicenseService.java:32)
29-Jul-2019 13:02:37	        at at.porscheinformatik.sonarqube.licensecheck.projectLicense.ProjectLicenseService.getProjectLicenseList(ProjectLicenseService.java:40)
29-Jul-2019 13:02:37	        at at.porscheinformatik.sonarqube.licensecheck.license.LicenseService.getLicenses(LicenseService.java:39)
29-Jul-2019 13:02:37	        at at.porscheinformatik.sonarqube.licensecheck.ValidateLicenses.getUsedLicenses(ValidateLicenses.java:53)
29-Jul-2019 13:02:37	        at at.porscheinformatik.sonarqube.licensecheck.LicenseCheckSensor.execute(LicenseCheckSensor.java:106)
29-Jul-2019 13:02:37	        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
29-Jul-2019 13:02:37	        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
29-Jul-2019 13:02:37	        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
29-Jul-2019 13:02:37	        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
29-Jul-2019 13:02:37	        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
29-Jul-2019 13:02:37	        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
29-Jul-2019 13:02:37	        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
29-Jul-2019 13:02:37	        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
29-Jul-2019 13:02:37	        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:408)
29-Jul-2019 13:02:37	        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:403)
29-Jul-2019 13:02:37	        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:400)
29-Jul-2019 13:02:37	        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:400)
29-Jul-2019 13:02:37	        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:360)
29-Jul-2019 13:02:37	        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
29-Jul-2019 13:02:37	        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
29-Jul-2019 13:02:37	        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:126)
29-Jul-2019 13:02:37	        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
29-Jul-2019 13:02:37	        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
29-Jul-2019 13:02:37	        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
29-Jul-2019 13:02:37	        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
29-Jul-2019 13:02:37	        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
29-Jul-2019 13:02:37	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29-Jul-2019 13:02:37	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
29-Jul-2019 13:02:37	        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29-Jul-2019 13:02:37	        at java.lang.reflect.Method.invoke(Method.java:498)
29-Jul-2019 13:02:37	        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
29-Jul-2019 13:02:37	        at com.sun.proxy.$Proxy23.execute(Unknown Source)
29-Jul-2019 13:02:37	        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
29-Jul-2019 13:02:37	        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
29-Jul-2019 13:02:37	        at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:65)
29-Jul-2019 13:02:37	        ... 23 more
29-Jul-2019 13:02:37	[ERROR] 
29-Jul-2019 13:02:37	[ERROR] 
29-Jul-2019 13:02:37	[ERROR] For more information about the errors and possible solutions, please read the following articles:
29-Jul-2019 13:02:37	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

Where is my mistake?

**Comment by Janpopan** [comment]
We found the problem.
Sonar:
Administration -> General Settings -> SonarQube License Check Plugin -> Key: licensecheck.projectlicense

There was a wrong entry. 

I think this configuration page is critical.
1) You can do such a mistake I did.
2) You can "clean" your configuration with "empty" defaults.

Should I open a new ticket on this useability "problem"?

**Comment by derkoe** [comment]
In the current SonarQube version you cannot disable this page anymore :(
You should do all config via Administration > Configuration > License check

Anyway we could make the parsing more stable and log errros but then you may not notice the wrong config. Better let it fail as it is

**Comment by derkoe** [comment]
Or maybe a better error message and fail?

**Comment by Janpopan** [comment]
There is a 3rd Sonar issue on this page:
Administration -> General Settings -> SonarQube License Check Plugin
You can only put 4000 Character or Byte in one of the boxes, this is hard wired in Sonar.
So what I have to do if I "clean" the boxes.
Is there a way to fill them with the default license list?

**Comment by derkoe** [comment]
As I said - please do *not* use this page for changing the plugin's settings. Please use Administration > Configuration > License check (in the menu on the top)

**Comment by Janpopan** [comment]
Yes I agree 100% with you. And we informed our team, I we will put this issue to our wiki.

But can you put this info into the readme.md and can you open a ticket at sonar? 

thanks a lot :-)
